/* csurrogate_params.h -- GENERATED by the v86 gate from the trained Python surrogate
   (cdet_surrogate.CDetSurrogate, seeds 130/131) and the resonance atlas (v80-v85).
   Do not edit by hand; regenerate via csurrogate.py. */
#ifndef CSURROGATE_PARAMS_H
#define CSURROGATE_PARAMS_H
static const double SURR_W[11]  = {-15.700325840893443, -0.76109970666561011, 0.094135467760962266, -0.36738724725830701, 0.015922126953977964, 0.0050062516323610739, 0.35225840755765891, 0.14243282362677584, 0.16176628869505064, 0.055303681600724054, 0};
static const double SURR_MU[10] = {4.4050043067531055, 0.61648405503558834, 2.5142857142857142, 11.41933073450468, 1.4097151450626244, 2.7076493777926181, 0.63809523809523805, 0.46027230308464606, 0.91238578073606758, 0};
static const double SURR_SD[10] = {1.1559781179593451, 1.1530269822153911, 0.70527651839328109, 2.118003968836673, 0.48632574943472434, 0.43868482037350498, 0.97222189928306879, 0.15967765596149572, 0.74558471399435078, 1.0000000000000001e-09};
static const double SURR_OFF_L6 = -2.9816691790695975;
static const double SURR_OFF_L4 = 0;
static const double ATLAS_ROOTS[3][2] = { {0.235, 0.832}, {0.19, 0.828}, {0.447, 0.939} };
/* geometry ids: 0 = (1,2,4), 1 = (1,3,5), 2 = (1,2,3) -- L=6 axis lines, level eps = 1 */
static const double ATLAS_STATIC_MID = 1.8284271000000001;
static const double ATLAS_STATIC_K   = -0.35451263537906286;
/* v102 side-by-side: surr_class2_static (the v84 K-flow above) DISAGREES with the v100 brute root-flow
 * reread by up to 0.021 over beta 28-44, with OPPOSITE slope (the L=8 static RISES with beta, per
 * parity_table.py FROZEN_CURVE_Z8 = {28:1.8268, 36:1.8378, 40:1.8417, 44:1.8449}). The v84 carrier is
 * retained as history; the decisive deep L=8 zero scan (the queued L=8 crossover test) is the arbiter. */
static const double REGIME_LO = 8.0, REGIME_HI = 12.0;   /* empirical beta*gap crossover (v80) */
/* v88 higher-order parameter sets (L=6 level 1, full axis-line configs):
 * n=4 (1,2,3,4): both roots resolved; transfer verified to max dev 0.024 (beta 14-24).
 * n=5 (1,2,3,4,5): lower root resolved (live dev 0.011); UPPER ROOT MARGINAL (s/n ~ 4 tail). */
static const double ATLAS_ROOTS_N4[2] = {0.156, 0.643};
static const double ATLAS_ROOTS_N5[2] = {0.402, 0.874};
/* v91 (the v90 two-window correction): the L=6 deep ~1.8 object is an ANCHORED, geometry-
 * independent static (z = A + B/beta; a = 1.824 +/- 0.022, b = -0.72 +/- 0.34), NOT a logit-flow
 * root -- the level-2 polynomial's deep (small-f) tail is beta-dependent (the creep), so small-f
 * roots must not be flown by the logit law. Anchor identity open: 2*sqrt(2)-1 vs 11/6.
 * v92 SCOPE CORRECTION (the anchor test): the A + B/beta law is EFFECTIVE for beta in [10, 32]
 * ONLY -- the trajectory rises through both v91 candidates above beta ~ 32. The deep-beta value
 * is MEASURED (multi-draw heavy-tail-honest protocol; single-draw CLT errors are invalid there,
 * kurtosis ~4500) as a_inf = 1.8437 +/- 0.0068 (beta 48-56 pool; beyond-56 constancy
 * unverified). Identification OPEN: the nearest framework constant is sqrt(2+sqrt(2)) = 1.84776
 * (octagon chord, Q(sqrt2)) at 0.60 sigma, but the null test saturates (83% rarity) -- NOT
 * RIGID; unique ID needs sigma ~ 0.0008 or the structural derivation. */
static const double ATLAS_L6_DEEP_A = 1.824, ATLAS_L6_DEEP_B = -0.72;   /* beta in [10,32] only */
static const double ATLAS_L6_DEEP_INF = 1.8437;   /* v92 honest measurement (+/- 0.0068)        */
/* v93 (the exponent-balance law): statics are integer-weighted means of the lattice's own
 * levels, z = mu* + ln(r)/(q beta) -- so they live in the spectrum's field (Q at L=6: the
 * octagon chord is excluded structurally). Finite menu in (1.80,1.88): {11/6, 13/7, 15/8}.
 * Frozen discriminator at beta=36/40 selected 11/6 at ~84:1 (z = 11/6 + 2.67(54)/(6 beta),
 * chi2/dof 0.09 over the honest pool). 13/7 disfavored, not dead; ln r measured, not derived. */
static const double ATLAS_L6_DEEP_ID  = 11.0 / 6.0;  /* v93 identified balance (q = 6)          */
static const double ATLAS_L6_DEEP_LNR = 2.67;         /* measured ln-ratio (+/- 0.54)            */
/* v95 STATUS (the degree bound, degree_bound.py): the bound is 7 = 2n+1, verified by a
 * symbolic census of the actual n=3 C_V (330 monomials, FULL support; v93's "8" and v94's
 * conjectured "6" both wrong). Balance positions come from exponent DIFFERENCES: the menu near
 * the object is {25/14, 9/5, 20/11, 11/6, 24/13, 13/7, 15/8, 17/9} -- and 24/13 = 1.84615
 * (q = 13, near-flat approach) sits 0.26 sigma from the v94 constant: the menu-vs-flatness
 * tension is DISSOLVED. Identification open among {13/7, 24/13}; 11/6 disfavored; the chord
 * remains excluded (menu all-rational). Closing route: the coefficient program (tau-average the
 * census coefficients, predict the zero outright). */
/* v94 STATUS (the side-by-side, law_sidebyside.py): the v93 identification is REOPENED -- the
 * out-of-sample test at beta = 44/52 scored ~9:1 for 13/7 against the frozen 11/6 line, while
 * the v93 frozen test had scored ~80:1 for 11/6; over the six honest points, 11/6 / 13/7 / a
 * CONSTANT 1.8467(21) all fit (chi2/dof 0.96 / 0.32 / 0.47). The constant reading puts the
 * octagon chord at 0.5 sigma and both menu rationals at 5-6.5 sigma -- the menu-vs-flatness
 * tension. Decisive theory item queued: the degree bound (n=3 may cap weights at 6, removing
 * 13/7 from the menu structurally). Both lines below stay live for scoring. */
static const double ATLAS_L6_DEEP_ALT     = 13.0 / 7.0;
static const double ATLAS_L6_DEEP_ALT_LNR = -3.21;
static const double ATLAS_L6_DEEP_CAND    = 24.0 / 13.0; /* v95: the q=13 menu member (flat) */
/* v96-v100 (the coefficient program; coefficient_flow.py, coefficient_phase2.py, delta_sector.py).
 * v96 PHASE 1: the background coefficient A(beta) of the (1,2)-window deep object measured ALIVE
 *   (A(44) > 0 at 4.6 sigma -> NO background-zero, no midpoint static); decay rate ~0.10-0.12 with
 *   prefactor curvature; the creep carrier identified as FAR-LEVEL ANTIPERIODIC IMAGES.
 * v99 PHASE 2: the heavy-tail estimator solved (importance sampling, ~31x; the s=0 integrand has
 *   tail index alpha ~ 0.55 -> plain-MC error bars are fiction). The FROZEN f2-polynomial measured
 *   at beta=36: A_IS = +0.370(11) e-9 (the v96 brute +0.277(45) was tail-biased low), frozen slope
 *   c1 ~ -202 e-9, ROOT s* = 0.00183(8) -> one-sector z_pol(36) = 1.8249(12). The v96 "FAITHFUL"
 *   claim is FALSIFIED at 3.4 sigma (physical(1.845) = +0.030(108) vs frozen-at-physical-point
 *   -0.339(14)): the freeze drops the delta1 antiperiodic images (O(1) in the tau->beta corner).
 * v100 THE DELTA SECTOR: that "second player" is NOT a standalone background but a delta1 x f2
 *   CROSS-TERM -- Delta(0; beta) ~ 0 at both beta (vanishes when level 2 is empty). Cross-slope
 *   d1 (matched-s secants over [0, 0.00376]): d1(28) = +41.8(13.2), d1(36) = +88.8(21.5) e-9,
 *   GROWING with beta; c1_eff = c1 + d1 moves the linear root 0.00183 -> 0.00327 toward the
 *   physical f2* = 0.00376 (right direction). The two-sector picture is one polynomial in
 *   (f2, delta1) with a beta-growing cross-coefficient.
 * MENU STATUS: open among {13/7, 24/13}; 11/6 disfavored; the chord excluded. The literal-rate
 *   menu bookkeeping (v93/v95) is suspect for HOLE-side monomials (the tau-corner saddle reduces
 *   effective hole rates) -- a tau-integrated re-derivation is queued. The EMPIRICAL pool stands.
 * CLOSURE (open, spec'd): the 13/7-vs-24/13 identification = the assembled root flow
 *   z(beta) = 2 - ln s*(beta)/beta with s*(beta) the root of A + c1_eff s + c2 s^2, needing the
 *   coefficient grid at beta in {36,44,52}; PREDICTION REGISTERED: z_assembled > z_pol at all beta.
 * v103 PRECISION CAVEAT: naive float64 silently drops the deep-beta far-level antiperiodic images
 *   (catastrophic 1-nf cancellation on corner configs -- certified by mpmath-200, fixed by
 *   stable_cdet.StableCDet). The FROZEN-side carriers (A_IS36, ZPOL36, XSLOPE) survive (A re-measured
 *   stable +0.3754(128) vs 0.370(11), 0.3 sigma; cross-term and faithfulness-falsified both survive).
 *   But the EMPIRICAL-POOL-fit carriers below (DEEP_ID/LNR 11/6, DEEP_ALT 13/7, DEEP_CAND 24/13, and
 *   the static family) were fit to a pool measured in naive float64; physical(1.845) re-measured stable
 *   = -0.1915(48) vs naive +0.030(108) (~4 sigma) -- the deep zero is NOT where naive placed it. These
 *   carriers carry a PENDING RE-FIT once the pool is re-measured on the stable engine. See
 *   PRECISION_RESULT.md.
 * v104-v107 RESOLUTION (the re-fit, now done -- deep_pool.py, deep_beta_resummation.py):
 *   v104: the stable integrand is STILL heavy-tailed (alpha ~ 1.06); median-of-means gives
 *     physical(1.845) = -0.077(60) ~ 0, so the pool SURVIVES (z(36) = 1.8428(40)); v103's
 *     "zero moves 4 sigma" was a single-draw fluctuation, RETRACTED.
 *   v105: the full robust pool z(36/44/52) = 1.8428(40)/1.8536(121)/1.8642(61) RISES and fits
 *     NO single menu line (best 13/7 chi2 6.5/2; all >3). The naive FLATNESS that drove v93-95
 *     to {13/7, 24/13} was a corrupted+heavy-tailed ARTIFACT; the menu-LINE identification is
 *     WITHDRAWN -- it is a FLOW, not a constant.
 *   v107: the assembled root flow reaches the asymptote from the RATE DIFFERENCE (loop-format
 *     resummation): rho_A = 0.1406(158), rho_c1 = 0.0225(95) -> z(inf) = 2 - (rho_A - rho_c1) =
 *     1.8818(184). This OVERTURNS the lower menu (24/13 1.9 sigma, 13/7 1.3 sigma, both
 *     disfavored) and RESURRECTS the HIGH end 15/8 = 1.875 (0.4 sigma; declared dead in v94/95
 *     on naive data) and 17/9 = 1.889 (0.4 sigma). The carriers below (DEEP_ID/LNR, DEEP_ALT,
 *     DEEP_CAND) are now SUPERSEDED history; the live asymptote is ATLAS_L6_Z_INF.
 * NOTE: surr_static_l6_deep_law / _alt below are the SUPERSEDED one-line menu lines (v93/v94),
 *   retained for historical scoring; surr_l6_zpol36 / surr_l6_cross_slope are the v99/v100 carriers. */
static const double ATLAS_L6_ZPOL36     = 1.8249;     /* v99 one-sector frozen-polynomial root, beta=36 */
static const double ATLAS_L6_ZPOL36_E   = 0.0012;
static const double ATLAS_L6_A_IS36     = 0.370e-9;   /* v99 IS-measured background at beta=36          */
static const double ATLAS_L6_C1_FROZEN  = -202.0e-9;  /* v99 frozen-polynomial slope at beta=36         */
static const double ATLAS_L6_F2STAR     = 0.00376;    /* physical f2 at the measured zero (z=1.845)     */
static const double ATLAS_L6_XSLOPE_B[2] = {28.0, 36.0};         /* v100 Delta cross-slope: beta points */
static const double ATLAS_L6_XSLOPE_D[2] = {41.8e-9, 88.8e-9};   /* v100 Delta cross-slope: d1 values   */
/* v104-v107 certified+robust deep-beta results (stable engine + median-of-means + loop-format). */
static const double POOL_STABLE_B[3]   = {36.0, 44.0, 52.0};            /* v105 robust pool: beta   */
static const double POOL_STABLE_Z[3]   = {1.8428, 1.8536, 1.8642};     /* v105 robust pool: z(beta) */
static const double POOL_STABLE_E[3]   = {0.0040, 0.0121, 0.0061};     /* v105 robust pool: errors  */
static const double ATLAS_L6_RHO_A     = 0.1406;   /* v107 dominant decay rate of A(beta)  (+/-0.0158) */
static const double ATLAS_L6_RHO_C1    = 0.0225;   /* v107 dominant decay rate of c1(beta) (+/-0.0095) */
static const double ATLAS_L6_Z_INF     = 1.8818;   /* v107 assembled asymptote 2-(rho_A-rho_c1)        */
static const double ATLAS_L6_Z_INF_E   = 0.0184;   /* -> overturns lower menu; 15/8 & 17/9 at 0.4 sigma */
/* v109 CAVEAT (stable C engine, cdet_stable_engine.c): v107's A(beta) was heavy-tail-biased LOW at high
 * beta (A(40) banked 0.119 vs true 0.267), so ATLAS_L6_Z_INF=1.8818 is an UNDERESTIMATE. The corrected
 * clean flow (A to beta=64) rises to z(64)=1.878 still climbing -> 15/8=1.875 is now DISFAVORED (the flow
 * passes through it), asymptote >=1.88 (17/9 or higher). But the extrapolation is UNSTABLE.
 * v110 PLATEAU (long-double engine to beta=120): there is NO plateau -- z RISES MONOTONICALLY through
 * EVERY menu rational (15/8 crossed at beta~61, 17/9 at ~74, 19/10 at ~87) to z(120)=1.920, still
 * climbing, with rho_A still decreasing (not converged). z(inf) is in [1.95,2.0], plausibly the trivial
 * z=2 (zero at the probe level) with slow 1/beta corrections. The menu-rational identification (v93-v107)
 * is RETRACTED: those were finite-beta crossings, not the asymptote. ATLAS_L6_Z_INF=1.8818 and all menu
 * carriers are finite-beta values, NOT z(inf). See PLATEAU_RESULT.md.
 * v111 RESOLVED: z(inf) = 2 (the bare probe level). Model comparison on the clean flow REJECTS the
 * exponential-gap/menu picture (chi2 622/7) in favour of a power-law: A ~ beta^-2.8, |c1| ~ beta^-0.54
 * (both rates ~0), so |c1|/A ~ beta^2.3 and z(beta) = 2 - 2.3*ln(beta)/beta -> 2 (general fit 1.991(2),
 * =2 within the leading-order truncation). The menu is a ln(beta)/beta approach to z=2. See ZINF_RESULT.md
 * and deep_beta_asymptote.py.
 * v112 DERIVED: A is corner-confined (J_A=beta^3*A -> const, so A ~ 1/beta^3); c1 is de-confined by the
 * smallest-gap level-2 channel (xi_2=2-mu=0.155, longest-range propagator), so J_c1=beta^3*|c1| ~ beta^2.7
 * and |c1| ~ beta^-0.3. The ratio |c1|/A ~ beta^2.7 forces z = 2 - 2.7*ln(beta)/beta -> 2. z(inf)=2 because
 * the probe level IS the smallest gap (slowest channel). See POWERLAW_DERIVATION_RESULT.md,
 * deep_beta_powerlaw_derivation.py.
 * v113 (single-channel sharpening tested): the phase IS carried by the n=2/level-2 sector and xi_2<xi_n
 * for all n (level 2 closest to mu) -- the compression to ONE channel is real (=v112). But the literal
 * c1=sum a_n exp(-xi_n beta) is FALSIFIED: c1 would then decay at rate xi_2=0.155 (3e6x over beta=24-120);
 * measured drop is 1.66x. The level-2 propagator SATURATES under tau-integration (int exp(-xi_2 tau)->1/xi_2),
 * giving a rate-0 power law, not an exp mode. gap (2-mu) = the de-confinement RANGE 1/xi_2=6.5 and the limit
 * z(inf)=2, NOT a beta-rate. See SPECTRAL_CHANNEL_RESULT.md, spectral_channel_test.py.
 * v114 (probe LOCK): z(inf)=2 is locked to level 2 because the probe MUST be the Fermi-surface (lowest
 * empty) level. Moving the probe to level 3 makes c1 DIVERGE as exp(+2.7 beta) -- a population inversion
 * (level 3 occupied, level 2 empty) forbidden by Fermi statistics. 'smallest gap' = 'Fermi surface' =
 * 'the only valid probe'. The mechanism does NOT generalize to arbitrary probes. See PROBE_LOCK_RESULT.md,
 * probe_generalization_test.py. */
static const double ATLAS_L6_Z_INF_RESOLVED = 2.0;  /* v111-v114 RESOLVED/DERIVED/LOCKED: z(inf)=2, the Fermi-surface probe level */
static const double ATLAS_L6_ZLAW_P         = 2.6;  /* v112: z = 2 - p*ln(beta)/beta finite-beta approach (ln(|c1|/A)~p ln beta) */
/* ============================================================================================
 * DEEP-BETA z(inf) -- CURRENT STATUS (v115 consolidation). The live answer is surr_l6_z_inf()=2.0.
 *   RESOLVED  (v111): exponential-gap/menu model rejected (chi2 622); z(inf)=2 (power-law approach).
 *   DERIVED   (v112): A corner-confined ~1/beta^3; c1 level-2 de-confined ~beta^-0.3; ratio beta^2.7
 *                     forces z = 2 - 2.6*ln(beta)/beta -> 2.
 *   SHARPENED (v113): the level-2 channel SATURATES (not an exp(-xi_2 beta) mode); gap (2-mu) = the
 *                     de-confinement range 1/(2-mu)=6.5 and the limit, not a beta-rate.
 *   LOCKED    (v114): the probe must be the Fermi-surface (lowest empty) level -- probe=3 diverges
 *                     (Fermi-forbidden population inversion). z(inf)=2 is not a coincidence.
 *   UNIVERSAL (v116): z(inf)=2 also holds across all SITE choices (scale flow ->2 for every geometry).
 *                     z(inf)=2 is DOUBLY universal (probe- and site-independent). The SIGN of (A,c1)
 *                     varies by geometry (opposite->physical root, same->none): the sign structure is
 *                     geometric, the scale is not.
 *   FRIEDEL   (v117): [momentum-id CORRECTED by v118/v119 -- see below] A's sign OSCILLATES with site separation at the Fermi
 *                     wavelength ~8 sites (2k_F from mu=1.845, small Fermi surface). The Fermi surface
 *                     governs BOTH: its GAP sets the scale z(inf)=2, its MOMENTUM sets the sign. Sign and
 *                     scale share one origin (the Fermi surface) via two channels.
 *   UNIFIED   (v118): moving mu shows BOTH the sign pattern and the z-flow are mu-INVARIANT in (1,2) -- the
 *                     engine is FROZEN so the Fermi surface is the DISCRETE level-1|level-2 boundary, fixed
 *                     for all mu in the window. v117's continuous-2k_F wavelength match was coincidental;
 *                     the sign's scale is set by the frozen boundary, not by mu. ONE discrete object governs
 *                     both scale and sign, rigid in mu; mu matters only when it crosses a level (v114).
 *   MAPPED    (v119): the ELEMENTARY frozen Friedel object rho(0,r)=FT of the occupied region is cube-
 *                     symmetric, SHORT-wavelength (~2-3 sites, wavevector (120,180)deg = the level-1|2
 *                     boundary modes), and EXACTLY mu-invariant (ZERO modes in the gap (1,2) -> occupied
 *                     set rigid; analytic proof of v118). A's sign is a determinant SUPERPOSITION of these
 *                     short elementary oscillations -- v117's ~8-site envelope was the superposition, not
 *                     the elementary scale. Same discrete Fermi surface sets the scale (z=2) and the sign.
 * Everything below (ATLAS_L6_Z_INF=1.8818, the menu rationals DEEP_ID/ALT/CAND) is SUPERSEDED
 * finite-beta history; surr_l6_z_inf_legacy() returns the old 1.8818 for the record only.
 * ============================================================================================ */
#define ATLAS_FRIEDEL_EDGE_INF 0.3472   /* v129: continuum rho Friedel edge kx/L (L=384), ~120deg/3-site end */
#define ATLAS_Z_INF_L8_MU1  1.41421356  /* v124: lowest-empty(L=8,mu=1)=sqrt2, the irrational z(inf) */

#endif

/* ============================================================================================
 * SIGN-SIDE carriers (v116-v119 consolidated into v120). The deep-beta SCALE is z(inf)=2 (above);
 * the SIGN is the geometric degree of freedom, and it is governed by the DISCRETE frozen Fermi
 * surface. Two distilled, exactly-checkable facts are carried here:
 *
 *  (a) The cube_hopping(6) spectrum is INTEGER-valued: eigenvalues -6..6 with the multiplicities
 *      below (sum 216). Because no eigenvalue lies in ANY open unit interval (n,n+1), the frozen
 *      occupied set is identical for every mu in such an interval -> the freeze is EXACTLY rigid in
 *      mu within a unit interval; the occupied set jumps only when mu crosses an integer. This is the
 *      analytic heart of v118's numerical mu-rigidity and v119's exact-mu-invariance, now carryable
 *      with NO eigendecomposition (surr_l6_gap_modes).
 *  (b) The elementary frozen Friedel object rho(0,r)=FT of the occupied region oscillates with a SHORT
 *      wavelength; its dominant in-plane wavevector is (120,180) deg = the level-1|2 boundary modes
 *      (ATLAS_L6_FRIEDEL_KX/KY). A's sign is a determinant SUPERPOSITION of these (v119); v117's
 *      ~8-site envelope was that superposition, not the elementary scale (v117 momentum-id corrected).
 *      [v121: rho(0,r) is now in C too -- cfriedel.c, plane-wave form, no eigenvectors, ~5e-11 vs Python.]
 *      [v122: the integer-spectrum mu-rigidity is CRYSTALLOGRAPHIC -- exact iff cos(2pi/L) rational iff L in
 *      {1,2,3,4,6}. The scale law z(inf)=lowest-empty-level and the Friedel law are universal (any L). The
 *      plane-wave propagator (cfriedel_L.c) makes the brute force O(N x MC), L-agnostic, no stored spectrum.]
 *      [v123: phase 2 BUILT -- cdet_planewave_engine.c (plane-wave determinant, any L, validated == stable
 *      engine at L=6). Scale law z(inf)=lowest-empty-level PROVEN multi-lattice: L=4 ->2, L=6 probe=3 ->3.]
 *      [v124: SCALING -- projector fast path (regroup g0 by distinct eigenvalue) EXACT, 73x at L=12, makes
 *      L=100 (1e6 sites) a day-long run; continuous freeze proves z(inf)=sqrt2 (irrational) at L=8; run_to_log
 *      harness + NaN guard for safe day-long unattended runs (streaming was already in place).]
 *      [v125: LARGE-L STUDY -- z(inf)(L)=lowest-empty(L) marches to mu as L->inf (gap~L^-3.3); ran L=100
 *      (1e6 sites) at 52s/pt via the fast path (probe_val=1.000192==prediction); signal vanishes as gap closes.]
 *      [v126: SIGNAL BUDGET -- c1 binds (relErr(c1)~gap^-0.47, relErr(A) flat); MC budget to resolve z(inf)
 *      ~ L^3 ~ N (POLYNOMIAL, no exp wall); day-long L=100 run resolves a coarse z-flow. Launch recipe in result.]
 *      [v127: SELECTION RULE vs L -- sign(A) converges (bulk), sign(c1) FRIEDEL-OSCILLATES in L (seed-stable,
 *      24-/32+/40-/48+), |c1|->0; v116 rule is a finite-gap Friedel phenomenon, goes MARGINAL in continuum. Prediction partially falsified.]
 *      [v128: sign(c1) in L has NO Friedel period -- period-16 FALSIFIED (28/44, 36/52 mismatch, seed-stable); it is
 *      ARITHMETIC JITTER (which multiplet is lowest-empty). v119 contrast: A integrates the sea (clean, converges), c1 picks one multiplet (jitters).]
 *      [v129: A's CONTINUUM FRIEDEL WAVEVECTOR -- rho's Fermi-surface edge converges kx/L 0.425->0.347 (~120deg,
 *      3-site end) as L->inf; v119's (120,180) confirmed as a convergent continuum feature (L=6 sampling of the fixed FS).]
 *      [v130: CONSOLIDATION -- surrogate carriers surr_lowest_empty/surr_friedel_edge added (match python exactly);
 *      brute re-stamped (ED anchor); hybrid header merged. Three-way side-by-side z(inf)=lowest-empty AGREES; no numerical drift.]
 *      [v131: CoS PROTOTYPE (Kozik 2024) -- verified a subset-convolution (2^n n^2) reorganization of C_V reproduces
 *      the engine to machine precision; honest cost: 3^n combine only beats it at n>=12, det cost (2^n n^3) dominates. Integration list in result.]
 *      [v132: INTEGRATION #1 (supplement) -- fast principal minors (Schur recursion, O(2^n n^2)) + subset-conv reproduce
 *      the engine's full C_V to 3e-15; computes the connected determinant at O(2^n n^2) vs O(2^n n^3 + 3^n). Engine untouched.]
 *      [v133: PHYSICAL MAPPING -- z(inf) is the single-particle ADDITION POLE (lowest-empty level): tracks the moving pole
 *      (v125), poles at eps_k by the v78 fugacity lemma. A real spectral observable (free now; self-energy #3 -> interacting).]
 *      [v134: INTEGRATION #3 step 1 (supplement) -- self-energy as the interacting upgrade of z. ED-verified: atom Sigma == closed
 *      form (1e-15); dimer addition pole == z at U=0, = eps+ReSigma at U>0. z = the Sigma=0 limit. Engine untouched.]
 *      [v135: INTEGRATION #3 step 2 (supplement) -- the DIAGRAMMATIC self-energy (connected-det order series + Dyson) converges
 *      to the exact Sigma (atom: 7e-6 @U.3 order 8). Radius ~pi/beta motivates the direct irreducible series (step 3). Engine untouched.]
 *      [v136: INTEGRATION #3 step 3 (supplement) -- the direct 1PI series has a LARGER radius R_Sigma (partition-fn zero, ~1.76)
 *      than the bare-G radius R_G (~0.80): past R_G bare DIVERGES, 1PI stays converged. Why Simkovic-Kozik compute Sigma directly.]
 *      [v137 CORRECTS v136: exact sigma_n via the Dyson recursion reproduce ED Sigma (1.9e-9 @U.3); their decay gives R_Sigma~0.84
 *      ~ R_G~0.73 -- NO radius advantage. v136's 1.76 was a contour-proxy artifact (contour enclosed Sigma's singularity). RETRACTED.]
 *      [v138 CONSOLIDATION: three paths (surrogate/plane-wave/python) agree (addition pole 5e-10); all v131-v137 advances live. README+QUICKSTART
 *      refreshed to the integration frontier. Learnings: plane-wave LD for deep-cancellation; self-energy needs engine wire-in + resummation.]
 *      [v139 STRESS TEST of the hybrid: robust (val 0.00e+00, fast==direct, NaN guard clean, 2.7M sites @193s, probe_val==surrogate). f64
 *      walls @beta~100, LD reaches >=200. Added input guards: delta<=0 refused, large delta warned, non-crystallographic+mode0/1 warned.]
 *      [v140 RESUMMATION/PRECISION (gravity-loop idea): our sigma_n have NO exact recurrence (no 15-digit rational resummation). Pade
 *      extends strong-coupling REACH (3e13->0.23 @U=3) not precision. The general accuracy lever = extended-precision arithmetic (LD/mpmath).]
 *      [v141 FOLD-IN + HINT: surrogate gains surr_interacting_pole(L,mu,U,nsig)=free pole + Hartree shift U*nsig (Sigma=0 recovers free).
 *      RATIONAL HINT (live): at FIXED density the atom self-energy IS rational (exact 1-term recurrence, [2/1] exact to 1e-15) -> the
 *      15-digit route lives in the SKELETON/bold expansion (grand-canonical nd(U) was the only non-rational piece). Lattice: open.]
 *      [v142 QUEUE #2 (SU(N)) step 1: the SU(N) atom EoS + the N-polynomial RECORD -- ln Z U-coeffs are exact degree-(j+1) polynomials
 *      in N (N=2..7 predict N=8,9,10 to 5e-9; ED-checked 2e-11). N-independent kernel -> any flavor number (incl N=6 Yb). Lattice: step 2.]
 *      [v143 QUEUE #2 step 2: the record SURVIVES HOPPING -- 2-site SU(N) lattice ED, ln Z coeffs stay degree-(j+1) in N (c1 deg2 predicts
 *      to 5e-5, U=0 factorizes to 1e-14). So the N-independent kernel -> any flavor number holds for the lattice. Production CDet+record: open.]
 *      [v144 QUEUE #2 step 3: the PRODUCTION EoS route -- first coeff from single-flavor g0 (d,d') x record (c1=-beta N(N-1)d^2,
 *      n1=-(N-1)d d') matches 2-site ED to 1e-7 for ALL N incl N=6 (NO N=6 diagonalization). Higher orders (full CDet+record): open.]
 *      [v145 QUEUE #2 step 4 + the gravity-loop HINT: 2nd-order EoS record persists (n2 low-deg poly in N, N=6 to 3e-4). The gravity
 *      recurrence->rational-GF->exact-resummation mechanism lives in N (not U): coeffs are poly in N -> finite recurrence in N (c1 3rd
 *      diff 7e-15) -> rational N-GF -> all-N EoS resums from a few small N (c1(6) exact). Same as gravity, in N; root 1 vs gravity cubic.]
 *      [v146 U-axis rational lead -> BOUNDARY: Sigma(U) rational IFF eigenvalues linear in U IFF interaction diagonal (atom: ||[Hkin,Hint]||=0).
 *      Hopping ||[Hkin,Hint]||=1.4 -> algebraic eigenvalues -> lattice Sigma ALGEBRAIC (branch points), NOT rational. 15-digit route = atom/local only.]
 *      [v147 CONSOLIDATION: 3 models at highest capability. Surrogate gains surr_sun_c1/surr_sun_n1 (SU(N) EoS coeffs, record x amplitude).
 *      ARCHITECTURE: frozen reference engine/ (194/194, never altered) + production hybrid (validates ==it, all caps) + surrogate (carriers).]
 *      [v148 cdet_lab.py UNIFIED CONTROL PLANE: every capability as swappable components from the terminal -- --target {eos,self-energy,addition-pole,
 *      double-occ,connected-det} x --method {ed,record,hubbard-i,diagrammatic,surrogate,hybrid,fast-minors,engine}. The surrogate is the 'surrogate' method.]
 *      [v149 cdet_shell.py: idiot-proof conversational front-end (clig.dev best practices) -- plain language -> interpret -> confirm -> run; did-you-mean on typos;
 *      'no' reverts but keeps named/saved configs. Thin safe layer over cdet_lab (the component map is the single source of truth).]
 *      [v150 BLIND-TEST HARDENING: fixed confirm-step trap (cancel/back/help/quit now work), N/n case collision, param validation (N>=1, U=abc warned),
 *      synonym word-boundary bug ('ed' inside 'connected'), lenient yes/no intent. Not possible to get stuck; always a labeled way back to start.]
 *      [v151 cdet_study.py SWEEP/STRESS HARNESS: scan a parameter for any (target,method); convergence detection; cutoffs --max-time / --accuracy-cutoff /
 *      --conv-tol; outputs log + data.csv + summary.json + plot.png + ASCII plot with convergence/breakdown/cutoff marked. NL-drivable in cdet_shell.]
 *      [v152 SU(N) step 5 (capstone): record-predicted EoS curve <n>(U). K=8 contour on small N -> record-predict N=6 (no SU(6) diag) -> Pade. Matches
 *      direct SU(6) ED to ~1-2% out to U~1.2 (10x the bare radius). Strong coupling needs conformal (v146 boundary). EoS exactly N-predictable; U-reach algebraic.]
 *      [v153 STRONG COUPLING REACHED: two-point Pade [2/2] bridges weak (lattice record) + strong (atom record m0=atomic limit) ends, both record-predicted from
 *      small N. Record-predicted SU(6) EoS matches direct ED across all U, hits U/t=2.3 (Kozik) at 2.4%, worst <5% to U=4. No SU(6) diagonalization.]
 *      [v154 2D THERMODYNAMIC LIMIT: the record is lattice-independent; leading EoS coeff n1=-(N-1)d d' transfers across geometry (2-site/ring/2D-cluster to 1e-8)
 *      -> replace cluster d,d' by converged 2D k-integrals -> SU(6) 2D n1=-0.5116, no diagonalization. Strong (atomic) anchor lattice-independent: two-point extends to 2D.]
 *      [v155 SECOND-ORDER coeff n2=(N-1)^2 a+(N-1) b: a=d(d'^2+0.5 d d'') is self-consistent Hartree (free derivs only, validated 2e-7), predicts n2(6) to 1.4e-4;
 *      dominant (N-1)^2 part exact in 2D thermodynamic limit (a_2D=0.005622, no diag); b=genuine bubble, subleading. Weak series exact through dominant 2nd order.]
 *      [v156 CONSOLIDATION of the v148-155 arc: single health gate (consolidation_v156.py, ~1s) re-proves three-model agreement + every capability since v147 (UI suite +
 *      SU(N) EoS weak->strong->2D->2nd order) live vs ED/k-integral anchors. Frozen engine/ 194/194 untouched. The consolidation rule is now standing protocol.]
 *      [v157 TRIPLE-RUN added to consolidation rule: run all three (surrogate/brute-force/hybrid), compare, improve the evolving two (never the frozen source), retest, record.
 *      Applied: hybrid auto-enables the bit-identical projector fast path for crystallographic L -> ~26x grid speedup, val still 0.00e+00. triple_benchmark.py.]
 *      [v158 CHAINED TWO-ROUND: round-1 terminal electron state (RNG stream) seeds round-2. Hybrid exposes terminal_state (print-only, val 0.00e+00). Continuation gives
 *      sqrt2 (1.39x) error reduction (vs zero-info same-seed rerun) AND non-cycling config expansion (9/10 vs deterministic 1-2 cycle). Same mechanism. chained_run.py.]
 *      [v159 TWO-PARTICLE chained run: two particles with exclusion (Pauli). Chained walk sweeps 10/10 pair-configs (no cycle), exclusion held. Continuation sqrt2 gain
 *      reaches BOTH 1-body A (1.44x) and 2-body interaction c1 (1.39x). Gains survive one->two particles and reach the interaction. two_particle_run.py.]
 *      [v160 CONFORMAL-BOREL resummation (field's order-axis tool, from web search): Borel transform + conformal map keyed to the complex Borel singularity |t_c|~1.05.
 *      Beats plain Pade 2-4x in the crossover (validated vs ED). Order axis = the real CDet frontier (lattice is easy); pairs with chained-continuation (orders/cost). sun_eos_conformal.py.]
 *      [v161 CONSOLIDATION of the v157-160 arc: health gate + triple-run benchmark, frozen baseline (194/194) retained as the parity anchor.
 *      Improvement cycle: safe set_freeze precompute is bit-identical but negligible (~0.6%, not added); low-rank freeze update identified, deferred as parity-risky. consolidation_v161.py.]
 *      [v162 LARGE-L plane-wave propagator (05_2d_lattice): free G0 straight from eps=-2t(cos kx+cos ky), O(L) memory, no eigenvector storage -> reaches 100x100 (beyond the 16x16 LMAX cap).
 *      Exact vs the numerical path (1.25e-16); TD-converged past ~12-16 sites (the method's strength: big lattices unneeded). square2d_pw_demo.c.]
 *      [v163 UNIFIED CLI: top-level `cdet` wraps the whole suite (validate/converge/resum/eos/run/sweep/lab/shell/info) with rich-optional output;
 *      self-contained (stdlib argparse, rich if present). `cdet validate` shows all gates green in one table. cdet.py.]
 *      [v164 DOUBLE OCCUPANCY observable: D=<n_up n_dn> = -(1/beta)dlnZ/dU per site, the Mott observable (E_int/site=U*D).
 *      Two independent ED routes agree to ~1e-10; conformal-Borel resums; physical Mott suppression with U. `cdet docc`. double_occupancy.py.]
 *      [v165 SUSCEPTIBILITIES: charge compressibility kappa=dn/dmu and spin chi_s=d<Sz>/dh, each cross-checked by a derivative + a fluctuation-dissipation route (~1e-7).
 *      Opposite Mott trends: kappa falls (incompressibility), chi_s rises (local moments); conformal-Borel resums. `cdet chi`. susceptibilities.py.]
 *      [v166 VISUALIZATION: built-in matplotlib figures (convergence/resummation/mott/summary) reproduced from the validated code paths -- cannot drift from the numbers.
 *      `cdet plot` renders a publication-quality results dashboard. plots.py.]
 *      [v167 PACKAGING/CI: pyproject.toml makes `pip install -e .` give a working `cdet` command (entry cdet:main); MIT LICENSE; GitHub Actions CI runs
 *      the frozen 194/194 gate + `cdet validate` + module self-tests on py3.9/3.11/3.12. packaging_check.py gates it.]
 *      [v168 DUAL LICENSE: switched from MIT to PolyForm Noncommercial 1.0.0 (free for academic/noncommercial -- educational+research institutions explicit) +
 *      a commercial license for business use (COMMERCIAL-LICENSE.md). packaging_check.py verifies the dual license.]
 *      [v169 DATA EXPORT: every validated observable (convergence/resummation/eos/docc/chi) -> CSV/JSON/HDF5, reproduced from the gated code paths (cannot drift),
 *      round-trip verified. CSV/JSON stdlib; HDF5 optional (h5py). `cdet export`. export.py.]
 *      [v170 NATIVE BINDINGS: optional pybind11 module cdet_core wraps the FROZEN engine primitives (G0_atom, density_exact, square2d_g0) read-only --
 *      bit-identical to the 194/194 engine (0.0e+00), ~10^6x faster than compile+subprocess. Opt-in build (pure-python install stays compiler-free). bindings/.]
 *      [v171 DOCKER: one-command deployment (Dockerfile + .dockerignore). Build bakes in the frozen 194/194 gate; ENTRYPOINT cdet, default CMD validate.
 *      docker_check.py gates the recipe; CI builds+validates the image. (docker build not run in the sandbox; recipe verified natively.)]
 *      [v172 THE WALL vs LATTICE SIZE: leading weak-coupling wall U_c(L)=1/chi0_max from the plane-wave dispersion (computable to 100x100). Near half-filling the
 *      small lattice is spuriously pessimistic; growing L pushes the wall back (1.64@4x4 -> 1.975 TD) -- lattice HELPS. Validated 5 ways. wall_vs_size.py, `cdet wall`.]
 *      [v173 THE WALL IS A TIDE: U_c(L) oscillates (BZ-quadrature commensuration). Period = 2pi/q* (measures the nesting vector: half-filling->2, mu=-2.8->3.68);
 *      even L exponential / odd L 1/L^2; amplitude calms as L grows. Validated 5 ways. wall_tide.py, `cdet tide`.]
 *      [v174 PRIME LATTICE SIZES: a Diophantine sieve on the wall. Primes are commensuration-blind -> worst-case samplers (~2.7x composite deviation);
 *      corr(#divisors,dev)=-0.39; the whole effect is the v173 curvature law on the grid-miss to q* (corr 0.96). Filling-dependent. wall_primes.py, `cdet primes`.]
 *      [v175 HALF-INTEGER LATTICES: twisted BC (theta=1/2 anti-periodic) + rectangular supercells. Twist does NOT heal the sieve (q-transfer grid theta-independent);
 *      a rectangular cell whose q-grid hits q* DOES (23x46 err 4e-4 vs 17x17 6e-2, prime dim OK). Tide/sieve are q-sampling artifacts. wall_twist.py, `cdet twist`.]
 *      [v176 CONSOLIDATION: all 4 wall modules onto one canonical core (wall_vs_size.chi0_max_rect; rect+twist upgrade in the base; square dev 0.0e+00). README wall section added.
 *      Side-by-side cross-check (consolidation_v176.py, `cdet crosscheck`): E shares one core; B<->E chi0(0)=dn/dmu (7e-13); D<->E same finite-radius phenomenon. All models retested green.]
 *      [v177 TRUE RADIUS: the nearest complex-U singularity of lnZ is a THERMAL Fisher pair at Im U=pi/beta (atom calibrated 0.0e+00), CLOSER than the RPA wall
 *      (ring L=3 R_true 2.90 < R_RPA 3.42, the v146 caveat) and -- being a global lnZ zero with no q-grid max -- WITHOUT the Diophantine sieve. wall_true_radius.py, `cdet trueradius`.]
 *      [v178 CONSOLIDATION: added INDEX.md -- the single map of the ~647-file package (architecture, dir map, all 19 CLI subcommands, the two arcs, where knowledge lives).
 *      README lists trueradius + points to INDEX; all doc references verified to resolve; no orphans; cdet validate 5/5; frozen 194/194.]
 *      [v179 TIER 0: implemented the connected-determinant (CDet) recursion itself -- C(V)=D(V)-sum_{v* in S} C(S)D(V\\S), det-weight per spin -- the method the package is named for but never had.
 *      Validated to machine precision: linked-cluster identity (2e-16, n=2..5), atom lnZ series (6e-17, orders 1..5), 2-site lattice vs ED (1e-9). Faithful low-order CDet, NOT a sign-problem result. cdet_connected.py, `cdet connected`.]
 *      [v180 UX POLISH: acted on a blind-user CLI review -- bare `cdet run` works (auto beta-hi + customize hint); `cdet sweep` per-point progress (study() progress hook); worked-examples help epilogs for run/sweep/lab;
 *      shell synonyms + friendlier no-match message; README 'Try this first' + folders-are-internals note. Engine/physics untouched; validate 5/5, frozen 194/194.]
 *      [v181 GUI: `cdet gui` launches a local stdlib-http browser console -- sliders (N,U,mu,beta,L) + one-click quick-run cards (eos/docc/chi/wall/trueradius/propagator/validate) with instrument readouts, teal traces,
 *      amber threshold lines, a Live toggle. Verified: page loads, every endpoint returns correct values (propagator 0.19944 = converge TD limit), 404 on unknown, validate 5/5. Front-end only; no new physics. cdet_gui.py.]
 *      [v182 GUI CSV + COPY-AS-CLI: sweep cards get a CSV download (reusing export._write_csv -> matches `cdet export` format, attachment headers); every card shows the exact runnable `cdet ...` command (live-synced to sliders) with a copy button.
 *      eos/docc/chi cards now compute at the suite reference (mu=1,beta=2) like the CLI so the copied command reproduces the shown value; mu/beta sliders drive the lattice cards. Verified commands run. Front-end only.]
 *      [v183 GUI RECENT RUNS: a server-side memory of explicit runs -- a `recent` strip of chips (card + slider values + result), click to restore+rerun, dedup, cap 8, clear; only Run (log=1) is remembered, not Live auto-reruns.
 *      Also fixed a real v181 bug: the sweep cards hung at high N (2-site ED is instant to N=4, 3.3s at N=5, hangs N>=6); capped GUI N at 4 (instant) + trimmed sweeps, larger SU(N) via the copy-as-CLI command. Front-end only.]
 *      [v184 GUI REBUILT AS A THIN WRAPPER (per Paul): the GUI now imports NO physics -- every card runs the real `cdet <subcommand> <flags>` via subprocess and shows its actual output; sliders just fill in flags. Removed the parallel path,
 *      the mu=1/beta=2 hardcoding, the N cap, and the GUI-side sweeps/CSV. Every subcommand is a card; nothing GUI-only; no reimplemented math; injection-safe (list argv, allow-listed). Core eos/docc/chi unchanged.]
 *      [v185 OPTIONAL HELP ASSISTANT: a toggle-on `assistant` panel in the console -- a self-contained RULE-BASED knowledge graph (cdet_assistant.py: 21 commands, 9 concepts, 6 workflows + keyword matcher), NOT an LLM (no model, no download, offline, instant).
 *      Answers what to do / capabilities in plain language with clickable command chips, alongside the docs; runs nothing. /api/assist endpoint; panel hidden by default. 10-query self-test passes. GUI still a pure wrapper.]
 *      [v186 ASSISTANT UPGRADE (researched chatbot best practices, applied): idf term-importance scoring over commands+concepts+workflows, difflib typo tolerance + light stemming, confidence gating with disambiguation, closest-match fallback,
 *      action/definitional intent signals, forward-path quick-reply suggestions, and follow-up via threaded context. Still offline/rule-based/runs-nothing; stdlib only; no physics; frozen engine untouched.]
 *      [v187 BLIND STUDENT TEST + onboarding fixes: installed/used the package blind as a first-year; the CLI on-ramp is good, but QUICKSTART contradicted the ./cdet front door and the assistant whiffed on beginner questions.
 *      Fixed: QUICKSTART friendly on-ramp (./cdet validate/converge/gui + assistant + CC=gcc note), Moller section relabeled (researchers); assistant beginner-SOS intent + foundational concepts (lattice, Hubbard model, ED, Monte Carlo). Docs/help only; no physics; frozen engine untouched.]
 *      [v188 BLIND EXPERT TEST (Moller) + benchmark surfacing: ran the blind test as a skeptical domain expert; all named capabilities verify (engine 194/194, bench_qss 12655x@n=2048, fast_minors O(2^n n^2)=3e-15 vs engine, self_energy honestly R_Sigma~R_G retraction kept, lab control plane, cv.py MC 70-80x, size-axis oracles).
 *      Friction: benchmarks scattered with no front door -> added `cdet bench` (engine speedup + reproducible index), surfaced in info/README/QUICKSTART/GUI card/assistant (benchmarks workflow; 'run benchmarks' no longer collides with `run`); reworded the 'What to show Moller' section self-contained. Honest gap stated: no production DiagMC sampler (Tier 2). Interface/docs only; frozen engine untouched.]
 *      [v189 CONNECTED-DETERMINANT MONTE CARLO (cdet_diagmc.py): added the DiagMC sampler the package described but lacked. Importance-sampled per-order coeffs + a grand-canonical Metropolis walker, sharing the validated cdet_connected kernel; reproduces exact ln(Z/Z0) within error bars (self-test).
 *      Measures the sign wall as the across-order series <sign>=|sum a_n U^n|/sum|a_n|U^n collapsing toward the radius (cost ~1/<sign>^2); does NOT defeat it (NP-hard), bounded by 2^n, validated on atom+2-site. Wired into cdet diagmc / info / GUI card / assistant. Frozen engine untouched.]
 *      [v190 BLIND INTERMEDIATE-STUDENT TEST + fixes: installed/used blind as an intermediate user. Found+fixed a real crash -- `cdet sweep` raised TypeError ('str' is not a mapping) because cmd_sweep passed the --base flag string where study() wants a base-params dict; now passes {} (evaluator supplies defaults). Verified CLI+GUI.
 *      Also: README's `pip install -e` lead failed on Ubuntu 24 (PEP 668) -- added venv/--break-system-packages note; surfaced that `cdet export <dataset>` takes a positional (eos/chi/...). No physics; frozen engine untouched.]
 *      [v191 ADVERSARIAL CHAOS CONSOLE TEST + hardening: hammered the CLI/GUI with garbage, unicode, injection, and absurd inputs. Injection is inert (no shell; float casts + allow-list reject it; GUI returns clean JSON errors). Fixed real self-DoS/nan: diagmc --nmax capped at 8 / floored at 1, --samples floored at 100, sweep point list capped at 60 + a 120s budget (graceful stop), and diagmc now rejects non-finite/non-positive beta/mu/U. No physics; frozen engine untouched.]
 *      [v192 BLIND LIFECYCLE TEST + interruption resilience: used it like a distractible user (Ctrl-C, kills, restarts, walk-away). SIGINT already clean ('interrupted.'); cache read already tolerant. Fixed: interrupted `cdet sweep` lost all work -> now data.csv written+flushed per point, log flushed per line, Ctrl-C caught so summary.json finalizes with a stop reason (partial results preserved). GUI restart on a busy port dumped an OSError traceback -> now auto-finds the next free port with a friendly note (or a clear all-busy message). Cache write now atomic (temp + os.replace). No physics; frozen engine untouched.]
 * ============================================================================================ */
static const int ATLAS_L6_MULT[13] = {1,6,12,14,27,36,24,36,27,14,12,6,1}; /* cube_hopping(6) eig -6..6, sum 216 */
static const int ATLAS_L6_FRIEDEL_KX = 2;  /* dominant elementary Friedel wavevector, x: 2*(2pi/6)=120 deg */
static const int ATLAS_L6_FRIEDEL_KY = 3;  /* dominant elementary Friedel wavevector, y: 3*(2pi/6)=180 deg */
