"""exponent_balance.py (v93; STATUS REVISED v94) -- THE EXPONENT-BALANCE LAW.
[v99 revision, coefficient_phase2.py: the LITERAL-RATE bookkeeping below (rates |mu - eps| read
off occupancy deviations) is suspect for HOLE-side monomials -- the tau-corner saddle reduces
effective hole rates (the delta1 antiperiodic images contribute at O(1) at the zero). The menu
positions need a tau-integrated re-derivation; the L=8 exact balance check and the empirical
pool stand.]
[v95 revision, degree_bound.py: the MENU below is superseded -- the true bound is 7 = 2n+1
(not 8; the up determinant carries the external vertex), and balance positions come from
exponent DIFFERENCES, giving the richer menu {25/14, 9/5, 20/11, 11/6, 24/13, 13/7, 15/8, 17/9}
near the object. The LAW, the field theorem, and the L=8 verification stand; this module's menu
gate tests its own v93-recorded computation as history.]
[v94 revision, law_sidebyside.py: the 11/6 identification below is REOPENED -- it did not
survive the out-of-sample side-by-side (beta = 44/52 scored ~9:1 for 13/7 vs the frozen 11/6
line; a constant 1.8467(21) also fits, reviving the chord and straining the menu). The LAW's
derivation, the field theorem, and the L=8 verification stand; the v93 frozen-test record below
is kept as history, and this module's gates test that record. The degree bound (weights <= 6 at
n = 3?) is the queued decisive item.]
THE LAW: the structural route the bridge tool
named primary (v92), executed. The deep static's position is DERIVED, the field question
answered, and a frozen discriminator measured.

THE LAW (derivation sketch, checks below). By the v78 lemma, in a saturated window all
mu-dependence enters through occupancy deviations dev_i = e^{-beta|mu - eps_i|} (particle f_eps
above mu, hole delta_eps below), and the stripped <C> is a FINITE polynomial in the deviations
(4x4 matrices x 2 spins -> each weight <= 8). A zero locks where two monomials balance:
c_1 prod dev^{w} = -c_2 prod dev^{w'}, giving

    mu* = (sum_i w_i eps_i) / (sum_i w_i),   approach  z(beta) = mu* + ln(r)/(q beta),  q = sum w_i

-- an INTEGER-WEIGHTED MEAN OF THE LATTICE'S OWN LEVELS, with the one-spine 1/beta approach
(v85) built in.

FIELD THEOREM (answers tau0/tau1): mu* lies in the field generated by the spectrum -- Q at L=6
(integer levels), Q(sqrt2) at L=8. The octagon chord sqrt(2+sqrt2) is NOT a weighted mean of
integer levels: EXCLUDED STRUCTURALLY at L=6. No cross-anchor mixing; each lattice's statics
live in its own anchor field.

L=8 VERIFICATION (exact, sympy): the (1,1) balance of the next-nearest pair (2sqrt2-2, 2sqrt2)
is 2sqrt2-1 = 1.8284 -- the v84 static EXACTLY; the rejected 1.707 is the naive adjacent
midpoint (sqrt2+2)/2. Both v84 facts accommodated.

THE FINITE MENU, L=6 window (1,2), in (1.80, 1.88) with total weight <= 8:
    11/6 (q=6),  13/7 (q=7),  15/8 (q=8)  -- 15/8 excluded by the honest pool (4.6 sigma).

THE FROZEN DISCRIMINATOR (predictions registered from the z(48)/z(56) pool BEFORE measuring):
    11/6 route: z(36) = 1.8475, z(40) = 1.8461;   13/7 route: z(36) = 1.8369, z(40) = 1.8389.
MEASURED (honest dense multi-draw): z(36) = 1.8450 +/- 0.0030, z(40) = 1.8457 +/- 0.0046.
    11/6: chi2 = 0.65 / 2 pts;  13/7: chi2 = 9.5 / 2 pts  ->  ~84:1 likelihood ratio for 11/6.
GLOBAL FIT (all four honest points): z = 11/6 + 2.67(54)/(6 beta), chi2/dof = 0.09.

VERDICT: the deep static is identified as the RATIONAL 11/6 (q=6 balance; ln r = +2.7(5)) at
~2.6 sigma via the frozen test -- a tau0-side (Q) constant, as the field theorem requires. The
v92 bridge verdict is upgraded from "NOT RIGID, one-of-many" to "derived menu + frozen-test
selection": the alphabet collapsed from 13 members to a 3-member derived menu before the data
spoke. HONEST SCOPE: 13/7 disfavored, not dead (1.5-2 sigma); the residue ratio r ~ 14 is
measured, not yet derived (queue); the (2,3)-window kill-shot probe came back INCONCLUSIVE --
that window is SUPPRESSED (|<C>| <~ 0.04 e-9 at beta = 20-28 throughout, ~30-50x below the (1,2)
window; only non-reproducing noise crossings), itself a datum (queued).
"""
import numpy as np
from fractions import Fraction as F
from slice_scaling import FastCDet
from symmetry_reduction import cube_hopping

HONEST = {36.0: (1.8450, 0.0030), 40.0: (1.8457, 0.0046),
          48.0: (1.846, 0.009), 56.0: (1.8407, 0.0103)}
FROZEN = {"11/6": {36.0: 1.8475, 40.0: 1.8461}, "13/7": {36.0: 1.8369, 40.0: 1.8389}}
MU_ID, Q_ID, LNR = F(11, 6), 6, 2.67   # the identified balance and its measured ln-ratio


def menu_l6_window12(lo=1.80, hi=1.88, wmax=8):
    """the finite exponent-balance menu: weighted means of levels {0,1,2,3} with particle
    weights on {2,3}, hole weights on {1,0}, total weight <= wmax."""
    out = set()
    for tot in range(2, wmax + 1):
        for a in range(tot + 1):
            for b in range(tot + 1 - a):
                for c in range(tot + 1 - a - b):
                    d = tot - a - b - c
                    if a + b == 0 or c + d == 0:
                        continue
                    mu = F(2 * a + 3 * b + c, tot)
                    if F(int(lo * 1000), 1000) < mu < F(int(hi * 1000), 1000) and mu != 2:
                        out.add(mu)
    return sorted(out)


def law(beta, mu=MU_ID, q=Q_ID, lnr=LNR):
    return float(mu) + lnr / (q * beta)


def _selftest():
    import sympy as sp
    ok = True
    r2 = sp.sqrt(2)
    l8 = sp.simplify(((2 * r2 - 2) + 2 * r2) / 2 - (2 * r2 - 1))
    print(f"L=8 (1,1) balance == 2*sqrt2-1 exactly: {l8 == 0} (gate); naive adjacent midpoint "
          f"{float((r2+2)/2):.4f} = the v84-rejected 1.707")
    ok = ok and l8 == 0
    m = menu_l6_window12()
    print(f"finite menu (1.80,1.88), weight<=8: {[str(x) for x in m]} (gate == [11/6, 13/7, 15/8])")
    ok = ok and m == [F(11, 6), F(13, 7), F(15, 8)]
    chi = {k: sum(((HONEST[b][0] - p) / HONEST[b][1]) ** 2 for b, p in d.items())
           for k, d in FROZEN.items()}
    lr = float(np.exp((chi["13/7"] - chi["11/6"]) / 2))
    print(f"frozen discriminator: chi2(11/6) = {chi['11/6']:.2f}, chi2(13/7) = {chi['13/7']:.1f} "
          f"-> likelihood ratio {lr:.0f}:1 (gates: chi(11/6)<2, chi(13/7)>6, LR>20)")
    ok = ok and chi["11/6"] < 2 and chi["13/7"] > 6 and lr > 20
    devs = [abs(law(b) - z) / e for b, (z, e) in HONEST.items()]
    print(f"global 11/6 law z = 11/6 + {LNR}/(6 beta) vs all honest points: max dev "
          f"{max(devs):.2f} sigma (gate <= 1)")
    ok = ok and max(devs) <= 1
    # field theorem spot-check: the chord is not in the menu (irrational), 11/6 is
    chord = float(np.sqrt(2 + np.sqrt(2)))
    print(f"field theorem: menu is rational (tau0-side Q) -- chord {chord:.5f} excluded "
          f"structurally (gate: not within 1e-9 of any member)")
    ok = ok and all(abs(float(x) - chord) > 1e-9 for x in m)
    # live engine: strong bracket at beta=36 (stored -1.114 +/- 0.060 at mu=1.864; +0.80 at 1.800)
    cd = FastCDet(cube_hopping(6), beta=36.0, to=0.7, ti=0.2)
    rng = np.random.default_rng(1013)
    vals = []
    for mu in (1.800, 1.864):
        ms = []
        for k in range(2):
            T = rng.uniform(0, 36.0, size=(2048, 3))
            v = np.array([cd.C_V([(1, float(t[0])), (2, float(t[1])), (4, float(t[2]))],
                                 float(mu)).real for t in T])
            ms.append(float(v.mean()))
        vals.append(float(np.mean(ms)))
    print(f"live engine beta=36 strong bracket x1e9: {[round(x*1e9,3) for x in vals]} (gate +,-)")
    ok = ok and vals[0] > 0 > vals[1]
    print("exponent-balance self-test (L=8 exact; menu; frozen test; global law; field; live):",
          "PASS" if ok else "FAIL")
    return ok


if __name__ == "__main__":
    _selftest()
